In [7]:
import numpy as np

In [9]:
X = np.array([[1,2],
              [3,4],
              [1,2],
              [3,4]])
y = np.array([1, 2, 3, 4])

In [26]:
# cari jumlah data yang ingin di split
#n_samples = len(X)
n_samples = 14
indices = np.arange(n_samples)
indices

# Tentukan jumlah split
n_splits = 3
fold_sizes = np.ones(n_splits, dtype=int) * int(n_samples / n_splits)
fold_sizes[: n_samples%n_splits] += 1

current = 0
for fold_size in fold_sizes:
    start = current
    end = fold_size + current
    
    # Seleksi index
    print(indices[start:end])

    # Update current index
    current = end

# indices[start_indices:end_indices]
# indices[0:5]
# indices[5:10]
# indices[10:14]

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13]


In [2]:
# index : 0 1 | 2 3
# size_fold = jumlah_data / n_split = 4 / 2 = 2

# index : 0 1 | 2 3
# shuffle : 1 3 0 2
# split : 1 3 | 0 2